Add state to metadata
uktrade/data-hub-api pull request #3340
Opened 2021-03-02 15:11 UTC by faissalMT

### Description of change
This adds the US State field for metadata along with the relevant seed data

### Checklist

* [ ] If this is a releasable change, has a news fragment been added?

  <details>
  <summary>Explanation</summary>
  
  A news fragment is required for any releasable change (i.e. code that runs in or affects production) so that a corresponding changelog entry is added when releasing.
  
  Check [changelog/README.md](https://github.com/uktrade/data-hub-api/blob/master/changelog/README.md) for instructions.
  
  </details>
  
* [ ] Has this branch been rebased on top of the current `develop` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

2021-03-02 15:13 UTC, vfarah-if commented on .gitignore
> +# pycharm
Remove for the global file

2021-03-02 15:14 UTC, vfarah-if commented on datahub/metadata/metadata.py
> +    TeamSerializer, StateSerializer,
Move this one line below

2021-03-02 16:23 UTC, ccp92 commented on datahub/metadata/metadata.py
> +    TeamSerializer, StateSerializer,
Resolved as part of the fixes for flake8

2021-03-02 17:34 UTC, tomkingston approved these changes
Looks good to me

2021-03-02 17:34 UTC, tomkingston commented on datahub/omis/order/pricing.py
> +            return x / 100  # noqa: E731
Looks good - I think you can remove the noqa comment now that you are using funcs instead of lambdas

2021-03-03 08:34 UTC, ambrozic requested changes

2021-03-03 08:34 UTC, ambrozic commented on .gitignore
> +
this is unnecessary change

2021-03-03 08:34 UTC, ambrozic commented on config/settings/local.py
> -from config.settings.common import *
this does not work and it breaks settings. this import order is actually important so that env variables are loaded before common settings module.

2021-03-03 08:34 UTC, ambrozic commented on config/settings/test.py
> -from config.settings.common import *
same as in `local.py`

2021-03-03 08:34 UTC, ambrozic commented on datahub/metadata/migrations/0007_initial_us_states.yaml
> +    state_code:
no newline at the end of file

2021-03-03 08:34 UTC, ambrozic commented on tests.sh
> +pytest --cov -s $@
no newline at the end of file

2021-03-03 08:34 UTC, ambrozic commented on datahub/metadata/models.py
> +
We need to discuss where and how is `State` model going to be used. Will it be used ie on `Company` model as a new field `address_state` including `country` but same `country` would be duplicated as `address_country` on model `Company`?

Also, `state_code` field in migrations is nullable but here it is not. Seems like `State` model was changes after  migration was created?

2021-03-03 09:19 UTC, ambrozic commented
Once all issues are addressed we should also squash as many commits as possible. This is small and focused amount of work and maybe even single commit is enough.

2021-03-03 09:49 UTC, elcct commented on config/settings/common.py
> +                              for email in env.list('DIT_EMAIL_INGEST_BLACKLIST', default=[])]
I would revert those code formatting changes as it makes code look out of place in comparison to the rest of the code base. There are some guidelines: https://github.com/uktrade/data-hub-api/blob/develop/docs/Coding%20style.md

2021-03-03 09:51 UTC, elcct commented on datahub/metadata/models.py
> +
I am not sure about the `State` name. It seems too generic and may be confusing without context. Maybe `CountryState` or similar would be more descriptive?

2021-03-03 09:54 UTC, elcct commented on datahub/omis/order/pricing.py
> +            return x / 100  # noqa: E731
I would not change the code that does not relate to the goal of the PR

2021-03-03 10:52 UTC, elcct commented on datahub/metadata/models.py
> +
@ambrozic has a good point regarding the relation to Country. Is there a reason why the relation is "state has a country" rather than "country has a state"?

2021-03-03 12:35 UTC, elcct commented
One more thing - we seem to have the US states already in the metadata - https://github.com/uktrade/data-hub-api/blob/9a176dfdab82077ba886ab181e8ff702abb99e5a/datahub/metadata/migrations/0001_administrative_areas.yaml
Is there a reason why this can't be reused?

2021-03-03 13:39 UTC, ambrozic commented on config/settings/common.py
> +
this change here is still unnecessary

2021-03-03 13:40 UTC, ambrozic commented on datahub/metadata/admin.py
> +class StateAdmin(ViewOnlyAdmin):
this class should be named `CountryStateAdmin`

2021-03-03 13:55 UTC, ambrozic commented on datahub/metadata/migrations/0007_initial_us_states.py
> +                ('name', models.TextField()),
`name` field on `CountryState` model inherited from `BaseConstantModel` should have `blank=True` but here in migration is going to have it set to `blank=False`. this migration should be recreated (or new one added that sets `blank=True` which is unnecessary)

2021-03-03 14:06 UTC, ambrozic commented
i hate to be that guy but we are also missing changelog news fragments file. because [rules](https://github.com/uktrade/data-hub-api/blob/9a176dfdab82077ba886ab181e8ff702abb99e5a/changelog/README.md).

2021-03-04 15:32 UTC, ccp92 commented
Following discussions in this PR, work has been re-done in administrative areas in #3342

2021-03-04 15:32 UTC, closed without merging