Add address state to company model
uktrade/data-hub-api pull request #3343
Opened 2021-03-05 16:42 UTC by faissalMT

### Description of change

Continuing from https://github.com/uktrade/data-hub-api/pull/3342 this adds the appropriate migrations and data model changes needed

### Checklist

* [ ] If this is a releasable change, has a news fragment been added?

  <details>
  <summary>Explanation</summary>
  
  A news fragment is required for any releasable change (i.e. code that runs in or affects production) so that a corresponding changelog entry is added when releasing.
  
  Check [changelog/README.md](https://github.com/uktrade/data-hub-api/blob/master/changelog/README.md) for instructions.
  
  </details>
  
* [ ] Has this branch been rebased on top of the current `develop` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

2021-03-08 17:34 UTC, tomkingston requested changes

2021-03-08 17:34 UTC, tomkingston commented on datahub/company/models/company.py
> +    address_state = models.ForeignKey(
These two fields have the same name -presumably you only want the second one?

2021-03-08 17:34 UTC, tomkingston commented on datahub/company/models/company.py
> +    registered_address_state = models.ForeignKey(
These two fields have the same name, presumably you only want the second one?

2021-03-08 17:34 UTC, tomkingston commented on datahub/company/migrations/0108_create_company_state_base_model.py
> +    ]
I cannot see the need for this migration if you are just altering this field again in the next migration?

2021-03-09 14:04 UTC, ambrozic commented on datahub/company/models/company.py
> -    address_county = models.CharField(max_length=MAX_LENGTH, blank=True)
do we want to remove `address_county` field?

2021-03-09 14:19 UTC, elcct commented on datahub/company/models/company.py
> +    address_state = models.ForeignKey(
I am not sure if `address_state` is a correct name - is this field going to contain administrative areas other than states? Maybe `address_administrative_area` could better describe it, the same with `registered_address_`.

2021-03-09 16:38 UTC, faissalMT commented on datahub/company/models/company.py
> +    address_state = models.ForeignKey(
We've changed it to `address_area_code`, is that ok?

2021-03-11 08:32 UTC, ambrozic commented on datahub/company/models/company.py
> +        related_name='companies_with_registered_state',
[lets rename this to `companies_with_registered_address_area_code` for the sake of consistency albeit it being long and ugly.](https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds)

2021-03-11 08:44 UTC, ambrozic commented on datahub/company/models/company.py
> +    address_state = models.ForeignKey(
should we go with just `address_area` and `registered_address_area` ?

2021-03-11 09:29 UTC, elcct commented on datahub/company/models/company.py
> +    address_state = models.ForeignKey(
I agree that `address_area` is better.

2021-03-12 08:20 UTC, ambrozic approved these changes

2021-03-12 09:43 UTC, elcct approved these changes

2021-03-12 11:31 UTC, merged