Add an API endpoint for the pipeline items data workspace dataset
uktrade/data-hub-api pull request #3353
Opened 2021-03-12 16:17 UTC by niross

### Description of change

Add a new API endpoint for pipeline items. This data will be consumed nightly by data flow for publishing on data workspace.

### Checklist

* [x] If this is a releasable change, has a news fragment been added?

  <details>
  <summary>Explanation</summary>
  
  A news fragment is required for any releasable change (i.e. code that runs in or affects production) so that a corresponding changelog entry is added when releasing.
  
  Check [changelog/README.md](https://github.com/uktrade/data-hub-api/blob/master/changelog/README.md) for instructions.
  
  </details>
  
* [x] Has this branch been rebased on top of the current `develop` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [x] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

2021-03-18 09:58 UTC, ambrozic requested changes

2021-03-18 09:58 UTC, ambrozic commented on changelog/pipeline-item-dataset-api-endpoint.api.md
> +A new pipeline item dataset endpoint (`GET /v4/dataset/pipeline-items`) was added to be consumed by data-flow and used in data-workspace.
based on `dataset/urls.py` should url be `/v4/dataset/pipeline-items-dataset` ?

2021-03-18 09:58 UTC, ambrozic commented on datahub/dataset/company_list/test/test_views.py
> +        ) if item.contacts.exists() else None,
doing `[o for o in queryset.all()] or None` will achieve same thing with one less call to database.

2021-03-18 10:26 UTC, ambrozic approved these changes

2021-03-19 09:55 UTC, PippoRaimondi approved these changes

2021-03-19 10:03 UTC, elcct approved these changes

2021-03-19 11:00 UTC, merged