Feature/cds 113 add trade agreements
uktrade/data-hub-api pull request #3385
Opened 2021-03-24 15:25 UTC by faissalMT

### Description of change

This adds trade agreement details to events.

### Checklist

* [ ] If this is a releasable change, has a news fragment been added?

  <details>
  <summary>Explanation</summary>
  
  A news fragment is required for any releasable change (i.e. code that runs in or affects production) so that a corresponding changelog entry is added when releasing.
  
  Check [changelog/README.md](https://github.com/uktrade/data-hub-api/blob/master/changelog/README.md) for instructions.
  
  </details>
  
* [ ] Has this branch been rebased on top of the current `develop` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

2021-03-26 14:58 UTC, tomkingston reviewed
Looks good, but this introduces a breaking change by making `related_trade_agreements` a required field on an existing endpoint - it seems like it would be best to make this field not required (unless you introduce a new endpoint with a new serializer).

2021-03-26 14:58 UTC, tomkingston commented on datahub/event/test/test_views.py
> +        """Tests specifying an end date before the start date."""
This docstring doesn't relate to the test

2021-03-26 14:58 UTC, tomkingston commented on datahub/event/serializers.py
> +        'event.TradeAgreement', many=True, required=True, allow_empty=True,
By making this a required field, you are introducing a breaking change to the API - I'm not sure what other services depend on this endpoint, but they will all break if they do not provide 'related_trade_agreements'. It seems like it would work out best all round if this field were not required.

2021-03-26 15:32 UTC, ccp92 commented on datahub/event/serializers.py
> +        'event.TradeAgreement', many=True, required=True, allow_empty=True,
I've pinged @ian-leggett a message about this.
The reason we marked the field as required is that the existing validation on the front-end form is driven by whether a field is marked as required on the API side.
Hopefully there will be a way to manage this solely on the front-end side as we don't want to introduce a breaking change if it can be avoided.

2021-03-26 16:23 UTC, ccp92 commented on datahub/event/serializers.py
> +        'event.TradeAgreement', many=True, required=True, allow_empty=True,
@tomkingston after chatting to Ian and looking at the [GDS design docs](https://design-system.service.gov.uk/patterns/validation/), we're probably going to go down the route of creating a new endpoint and serializer.
Do you think that would be ok to add to this existing PR or should we split that off?

2021-03-31 09:29 UTC, ccp92 commented
Please note when reviewing that a large chunk of this PR is the duplication of the V3 events tests to the V4 events tests.
The main difference between these two suites is that `related_trade_agreements_exist` and `related_trade_agreements` are not required on the V3 endpoint but are required on the V4 endpoint.

Similarly in the serializer file, the V4 class is the same as the V3 class but the fields are only required in the V4 class.

2021-03-31 12:23 UTC, tomkingston requested changes
Hi - looks good generally - I've left a few change requests, but hopefully they won't take too long.

2021-03-31 12:23 UTC, tomkingston commented on datahub/event/urlsv4.py
> +    path('event/<uuid:pk>', itemv4, name='itemv4'),
There is no need to name these `itemv4` and `collectionv4` - they are already url namespaced at the root with `api-v4`.

For consistency, it would be best to define both url types (`urls_v3` and `urls_v4`) in the 'urls.py' file - see https://github.com/uktrade/data-hub-api/blob/develop/datahub/search/urls.py for an example.

2021-03-31 12:23 UTC, tomkingston commented on datahub/event/test/test_views_v4.py
> +from operator import itemgetter
It would be best to avoid having a completely new test file for v4 especially as it is so similar to v3 - you could just mark the majority of the v3 tests with [pytest.parrametrize](https://docs.pytest.org/en/stable/parametrize.html) - to test each of the two urls - you probably want something similar to what is here: https://github.com/uktrade/data-hub-api/blob/develop/datahub/admin_report/test/test_views.py#L16

2021-03-31 12:23 UTC, tomkingston commented on datahub/event/test/test_views_v4.py
> +
You should add a test case for when `related_trade_agreements_exist` is True, but there are no trade agreements specified - presumably it should give a 400 response to say that `related_trade_agreements_exist` but no `related_trade_agreements` were specified.

2021-03-31 12:23 UTC, tomkingston commented on datahub/event/models.py
> +    related_trade_agreements_exist = models.BooleanField(null=True, blank=True)
`has_related_trade_agreements` sounds a bit better to me - there doesn't seem to be a convention across the project though so no need to worry about this one.

2021-03-31 14:22 UTC, faissalMT commented on datahub/event/serializers.py
> +    )
There are things that are using that data from the V3 endpoint, I think it'd be better if we kept it so things using V3 can still access that data

2021-03-31 15:36 UTC, elcct commented on datahub/event/models.py
> +    related_trade_agreements_exist = models.BooleanField(null=True, blank=True)
I agree with @tomkingston, I also prefer the `has_...`.

2021-03-31 15:48 UTC, faissalMT commented on datahub/event/test/test_views_v4.py
> +from operator import itemgetter
I'd like to avoid this just because it might make the relevant tests harder to find as well as change as these two apis diverge going forward

2021-03-31 15:54 UTC, faissalMT commented on datahub/event/test/test_views_v4.py
> +
If the user doesn't select anything on the frontend despite clicking 'yes' a `null` is sent back, the only time no trade agreements are sent are if 'no' is selected

2021-04-01 08:24 UTC, tomkingston commented on datahub/cleanup/test/commands/test_delete_orphans.py
> +    # Set up uthe state before running the command
Typo

2021-04-01 08:32 UTC, tomkingston commented on datahub/event/serializers.py
> +    )
I'm not quite sure what would be using these fields as they have only just been added? Since they are not required I don't mind them being left in though.

2021-04-01 08:46 UTC, tomkingston commented on datahub/event/test/test_views_v4.py
> +from operator import itemgetter
Given that the v3 serializer, endpoint and tests will need to be deleted once this is implemented I think that should be fine. However, it does make it very difficult to see what new tests have been added in this PR and the functionality in most cases should be exactly the same, so this does temporarily add a huge amount of code duplication (ie double the maintenance).

2021-04-01 09:39 UTC, tomkingston commented on datahub/event/test/test_views_v4.py
> +
It sounds like that is dependent on the frontend implementation stopping you do bad things, but the backend should be agnostic of that. At the moment you could end up with bad data being stored in the database, the API could be called with this input...
```
{
    has_related_trade_agreements: True,
    related_trade_agreements: [],
    ...
}
```
Which would result in non-sensical / inconsistent data being stored in the database - it should raise a 400 error to specify that this is bad input. 
Ideally you would also have test cases for the `PATCH` method to make sure that the input does not conflict with what is already stored in the database - ie when an existing event has `has_related_trade_agreements` set to True and then you PATCH with `related_trade_agreements = [] ` (or vice-versa), the data will end up being inconsistent, so this should also raise a 400 error.

2021-04-01 09:43 UTC, tomkingston commented on datahub/event/test/test_views_v4.py
> +
I think Chris mentioned just putting `has_related_trade_agreements` on the serializer but not the database model - that would get over the problem of inconsistent data so it would be less important to raise 400 errors when inconsistent data is received.

2021-04-01 09:50 UTC, faissalMT commented on datahub/event/serializers.py
> +    )
The frontend changes use it at the moment for displaying the data

2021-04-01 10:10 UTC, tomkingston commented on datahub/event/constants.py
> +    uk_japan = Constant('Japan', '05587f64-b976-425e-8763-3557c7936632')
Should Canada, India, Mexico, New Zealand, USA also appear here?

2021-04-01 11:13 UTC, faissalMT commented on datahub/event/constants.py
> +    uk_japan = Constant('Japan', '05587f64-b976-425e-8763-3557c7936632')
We're not really using them for any tests, and as far as I know these enums aren't for anything other than tests

2021-04-01 11:29 UTC, tomkingston commented on datahub/event/serializers.py
> +    )
Oh, sorry, should have been a bit more specific, I just meant the two related_trade_agreements fields which have just been added, but it looks like you have now moved these to only the v4 serializer so all good :+1:

2021-04-01 11:31 UTC, tomkingston commented on datahub/event/constants.py
> +    uk_japan = Constant('Japan', '05587f64-b976-425e-8763-3557c7936632')
Ah, I see, yeah, it looks like you only need these for tests etc so no need to add any more, unless anyone else thinks differently.

2021-04-01 16:02 UTC, faissalMT commented on datahub/event/serializers.py
> +    )
The v3 serializer still has `related_trade_agreements`, it just doesn't have `related_trade_agreements_exist` since the frontend doesn't really use it for anything aside from validation when submitting.

2021-04-06 14:53 UTC, tomkingston approved these changes

2021-04-06 15:30 UTC, ambrozic approved these changes

2021-04-06 16:26 UTC, merged