Add new Levelling Up service and event type
uktrade/data-hub-api pull request #3450
Opened 2021-04-20 15:37 UTC by peterhudec

### Description of change

Added a new service `Export Academy`.

* A Specific DIT Export Service or Funding / `Levelling Up` (Export interaction, Export service delivery)
* A Specific Service / `Levelling Up` (Other interaction, Other service delivery)
* Added `Levelling Up` to the list of event types

### Checklist

* [x] If this is a releasable change, has a news fragment been added?

  <details>
  <summary>Explanation</summary>
  
  A news fragment is required for any releasable change (i.e. code that runs in or affects production) so that a corresponding changelog entry is added when releasing.
  
  Check [changelog/README.md](https://github.com/uktrade/data-hub-api/blob/master/changelog/README.md) for instructions.
  
  </details>
  
* [x] Has this branch been rebased on top of the current `develop` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [x] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

2021-04-20 16:00 UTC, faissalMT approved these changes

2021-04-30 11:28 UTC, ambrozic requested changes

2021-04-30 11:28 UTC, ambrozic commented on datahub/metadata/migrations/0011_update_services.py
> +    ]
no newline at the end

2021-04-30 11:28 UTC, ambrozic commented on datahub/metadata/migrations/0011_update_services.yaml
> +# Race to Zero, including Science Based Targets
can this empty lines above be removed?

2021-05-04 09:59 UTC, ambrozic approved these changes

2021-05-05 13:18 UTC, merged