Canadian Company Address Area
uktrade/data-hub-api pull request #3452
Opened 2021-04-22 14:10 UTC by vfarah-if

### Description of change
DB management command for fixing postcodes for Canadian companies and updating the address area to match the fixed postcode where possible.

### Checklist

* [X] If this is a releasable change, has a news fragment been added?

  <details>
  <summary>Explanation</summary>
  
  A news fragment is required for any releasable change (i.e. code that runs in or affects production) so that a corresponding changelog entry is added when releasing.
  
  Check [changelog/README.md](https://github.com/uktrade/data-hub-api/blob/master/changelog/README.md) for instructions.
  
  </details>
  
* [X] Has this branch been rebased on top of the current `develop` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [X] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

2021-04-22 14:18 UTC, vfarah-if commented on datahub/dbmaintenance/management/commands/fix_ca_company_address.py
> +
Generate TEST data for Canada company so this can be viewed and understood for developers wanting to run the command locally

2021-04-22 17:12 UTC, tomkingston requested changes
It would be good to make some changes to the class inheritance on the management commands - there's also quite a few formatting changes, quite a few of which will probably become redundant after changing the structure as suggested.

2021-04-22 17:12 UTC, tomkingston commented on datahub/dbmaintenance/management/commands/base_fix_company_address.py
> +    """
This will add another management command that I don't think you will ever be using (`./manage.py base_fix_company_address ...`) - it's just used as a base class for other commands: `fix_ca_company_address` and `fix_us_company_address`. In fact, this code shouldn't really sub-class `BaseCommand` at all and you should ship out most of this functionality into its own fixer function (although it is probably easier to use a class because you have pretty much already built that), something like this would be better:

```
# dbmaintenance/fixers/addresses.py

class AddressFixer():
    def __init__(self, country_id, revision_comment, zip_states, postcode_replacement):
        self.country_id = country_id
        self.revision_comment = revision_comment
        self.postcode_replacement = postcode_replacement
        self.zip_states = zip_states
    
    def run(self):
        with reversion.create_revision():
            self.fix_postcodes_and_areas()
            reversion.set_comment(self.revision_comment)

   ...other methods

# management/commands/fix_ca_company_address.py
class Command(BaseCommand):
    help = 'Fix Canadian Company address postcodes for the purpose of setting address areas'

    def handle(self, *args, **options):
        address_fixer = AddressFixer(
            country_id=Country.canada.value.id,
            revision_comment='Canada area and postcode fix.',
            zip_states=CA_ZIP_STATES,
            postcode_replacement=CountryPostcodeReplacement.canada.value,
        )
        address_fixer.run()
```

2021-04-22 17:12 UTC, tomkingston commented on datahub/dbmaintenance/management/commands/base_fix_company_address.py
> +            raise CommandError('Country Id is mandatory')
You should really make sure that all lines of code are covered by a test - I expect you could get all of these in one go using a `pytest.parametrize`

2021-04-23 08:42 UTC, vfarah-if commented on datahub/dbmaintenance/management/commands/fix_ca_company_address.py
> +            force_color)
I see that makes sense, wont do that again

2021-04-23 08:48 UTC, vfarah-if commented on datahub/dbmaintenance/management/commands/base_fix_company_address.py
> +
I could not do it on one line, flake8 issue but I did indent it the same

2021-04-23 08:49 UTC, vfarah-if commented on datahub/dbmaintenance/management/commands/base_fix_company_address.py
> +    """
Fixed with resolver logic - probably could have moved my base class into the base class but I think I favoured this implementation so kept it similar

2021-04-23 08:54 UTC, vfarah-if commented on datahub/dbmaintenance/management/commands/base_fix_company_address.py
> +            raise CommandError('Country Id is mandatory')
Yes I was going to wait until I got feedback on the inheritance structure which I had a feeling that would be rejected but for other reasons I had in my mind. I was about to do a test for that but now feel your structure lends to not needing this original implementation. I also think testing constructor exceptions is unnecessary but I know that we need 97% coverage so I would have had to do that test as soon as I pulled this from draft. Tom thanks very much for the great feedback!

2021-04-26 09:52 UTC, vfarah-if commented on changelog/ca-area.db.md
> +Address aea update made more reliable and refined by only updating active companies only containing a D-U-N-S number, guaranteeing the address data to be reliable.
Typo to be fixed

2021-04-27 08:30 UTC, tomkingston reviewed
Really good to see the common code moved out to its own resolver module. 

There are still quite a few issues on code style / formatting. You should also use keywords rather than positional arguments wherever possible to make it clearer what you function calls are doing. Hopefully it won't take long to clear up.

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/resolvers/company_address.py
> +                          f'from "{company.registered_address_postcode}"'
It is best to avoid using the `\` line continuation - this can be written as:
```
log_message = (
    f'Updating registered postcode from "{company.registered_address_postcode}"'
)
```

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/resolvers/company_address.py
> +                company.registered_address_postcode)
Closing brackets should really be on a new line:

```
company.registered_address_postcode = self.format_postcode(
    company.registered_address_postcode
)
```

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/test/commands/test_fix_ca_company_address.py
> +    """
These arguments are indented too far:
```
def test_ca_company_with_address_data_only_will_generate_address_area(
    post_code,
    area_code,
):
```

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/test/commands/test_fix_ca_company_address.py
> +):
These arguments are indented too far:

```
def test_command_leaves_invalid_postcodes_in_original_state_with_no_area(
    post_code,
    expected_result,
):
```

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/resolvers/company_address.py
> +    ):
These arguments are indented too far:
```
    def __init__(
        self,
        country_id,
        revision_comment,
        zip_states,
        postcode_replacement,
    ):
```

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/test/commands/test_fix_ca_company_address.py
> +    )
Please use keyword arguments - at the moment it is not clear what any of these `None`s mean without referring back to the class definition - you are also susceptible to any future changes in the order of the arguments.

```
    resolver = CompanyAddressResolver(
        country_id=None,
        revision_comment=None,
        zip_states=None,
        postcode_replacement=CountryPostcodeReplacement.canada.value,
    )
```

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/test/commands/test_fix_ca_company_address.py
> +):
These arguments are indented too far

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/test/commands/test_fix_ca_company_address.py
> +):
These arguments are indented too far

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/test/commands/test_fix_ca_company_address.py
> +):
These arguments are indented too far

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/test/commands/test_fix_us_company_address.py
> +    )
You should use keyword arguments to make it clear what this is doing:
```
    resolver = CompanyAddressResolver(
        country_id=None,
        revision_comment=None,
        zip_states=None,
        postcode_replacement=CountryPostcodeReplacement.united_states.value,
    )
```

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/test/commands/test_fix_us_company_address.py
> +):
These arguments are indented too far

2021-04-27 08:30 UTC, tomkingston commented on datahub/dbmaintenance/test/commands/test_fix_us_company_address.py
> +):
These arguments are indented too far

2021-04-27 08:54 UTC, vfarah-if commented on datahub/dbmaintenance/resolvers/company_address.py
> +    ):
Good spot

2021-04-27 08:58 UTC, vfarah-if commented on datahub/dbmaintenance/resolvers/company_address.py
> +                          f'from "{company.registered_address_postcode}"'
Strange I was sure I tried this and got flake8 issues - fixed

2021-04-27 14:41 UTC, tomkingston approved these changes

2021-04-28 18:11 UTC, elcct approved these changes

2021-04-29 07:14 UTC, merged