Add the COP26 service and its child services
uktrade/data-hub-api pull request #3466
Opened 2021-04-30 11:08 UTC by peterhudec

### Description of change

Add the COP26 service and its child services:

* Adaptation and Resilience
* Clean Transport, including EV100
* Energy Transitions, including RE100 and EP100
* Finance, including TCFD
* Participation at Glasgow/getting involved with COP26
* Nature, including supply chains
* Race to Zero, including Science Based Targets

### Checklist

* [x] If this is a releasable change, has a news fragment been added?

  <details>
  <summary>Explanation</summary>
  
  A news fragment is required for any releasable change (i.e. code that runs in or affects production) so that a corresponding changelog entry is added when releasing.
  
  Check [changelog/README.md](https://github.com/uktrade/data-hub-api/blob/master/changelog/README.md) for instructions.
  
  </details>
  
* [ ] Has this branch been rebased on top of the current `develop` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

2021-05-04 09:36 UTC, cgsunkel approved these changes

2021-05-04 10:16 UTC, elcct requested changes

2021-05-04 10:16 UTC, elcct commented on datahub/metadata/migrations/0011_update_services.yaml
> +    order: 17004.0
The order is duplicated. It should be distinct otherwise the service may show up in a random order.

2021-05-05 08:57 UTC, elcct approved these changes

2021-05-05 13:00 UTC, merged