Account Integration with BED Salesforce API
uktrade/data-hub-api pull request #3521
Opened 2021-05-28 14:45 UTC by vfarah-if

### Description of change

t's now possible to interact with BED and Salesforce using the BED salesforce API.

### Checklist

* [ ] If this is a releasable change, has a news fragment been added?

  <details>
  <summary>Explanation</summary>
  
  A news fragment is required for any releasable change (i.e. code that runs in or affects production) so that a corresponding changelog entry is added when releasing.
  
  Check [changelog/README.md](https://github.com/uktrade/data-hub-api/blob/master/changelog/README.md) for instructions.
  
  </details>
  
* [ ] Has this branch been rebased on top of the current `develop` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

2021-06-07 09:38 UTC, tomkingston approved these changes

2021-06-07 09:38 UTC, tomkingston commented on sample.env
> +BED_IS_SANDBOX=true
You are missing a new line

2021-06-07 09:38 UTC, tomkingston commented on datahub/bed_api/tests/conftest.py
> +def generate_high_level_sector(faker):
As a fixture, you don't really need to prefix this with `generate` - it's just a `high_level_sector`

2021-06-07 09:42 UTC, tomkingston commented on datahub/bed_api/entities.py
> +        self.is_sentiment = None
If all of these were just Nones - you could do something like this:
```
for key in self.data_mapping.keys():
    setattr(self, key, None)
```

2021-06-07 09:50 UTC, tomkingston commented on datahub/bed_api/entities.py
> +        self.is_sentiment = None
....or you could have the data_mapping like this...
 
```
class Account(BedEntity):
    data_mapping = {
       ...
        'company_number': {
            'bed_field': 'Company_Number__c',            
            'default': None,
        },
        ...
        'is_ftse_100': {
           'bed_field': 'FTSE_100__c',
            'default': False,
        },
        ...
     def __init__(self, *args, **kwargs):
        ...
       for key, value in self.data_mapping.items():
       setattr(self, key, value.get('default'))
       ...
```

2021-06-07 10:01 UTC, tomkingston commented on datahub/bed_api/entities.py
> +        self.is_sentiment = None
Actually, that init could then be on the base class since it is generic

2021-06-07 10:38 UTC, vfarah-if commented on sample.env
> +BED_IS_SANDBOX=true
Fixed

2021-06-07 10:52 UTC, vfarah-if commented on datahub/bed_api/entities.py
> +        self.is_sentiment = None
Fixed

2021-06-07 11:06 UTC, vfarah-if commented on datahub/bed_api/tests/conftest.py
> +def generate_high_level_sector(faker):
Fixed

2021-06-08 15:18 UTC, ambrozic requested changes

2021-06-08 15:18 UTC, ambrozic commented on datahub/bed_api/constants.py
> +        return result
`return [x.value for x in self._member_map_.values() if x.value != '']`

2021-06-08 15:18 UTC, ambrozic commented on datahub/bed_api/factories.py
> +        else:
this `else` here is redundant

2021-06-08 15:18 UTC, ambrozic commented on datahub/bed_api/repositories.py
> +            and response['totalSize'] >= 1
can this be `> 0` same as the line below?

2021-06-08 15:18 UTC, ambrozic commented on datahub/interaction/migrations/0001_initial_issue_types.yaml
> +  fields: {disabled_on: null, name: International Climate, order: 600.0}
missing newline

2021-06-08 15:18 UTC, ambrozic commented on datahub/interaction/migrations/0001_initial_policy_areas.yaml
> +  fields: {disabled_on: null, name: 'Race to Zero, including Science Based Targets', order: 6500.0}
missing newline

2021-06-08 15:43 UTC, ambrozic commented on datahub/bed_api/utils.py
> +        return data
this `else` is redundant and `elif` above could be just `if`

2021-06-09 07:02 UTC, vfarah-if commented on Makefile
> +	python -m black <Add File Here> --skip-string-normalization
I repeat this a lot as a developer and do does my team - as the the make file is for developers, will this hurt?

2021-06-09 07:07 UTC, vfarah-if commented on config/settings/test.py
> +BED_SECURITY_TOKEN = 'test-token'
Fixed

2021-06-09 07:09 UTC, vfarah-if commented on datahub/bed_api/data_context.py
> +class BedDataContext(DataContext):
Fixed

2021-06-09 07:20 UTC, vfarah-if commented on datahub/bed_api/entities.py
> +        return result
1. Great suggestion - looks a lot cleaner as you suggested
2. I don't think it is possible because of the case difference to start with, but id is an example of it being the same except for the case. But I am not sure I understood what you wanted me to resolve?

2021-06-09 07:24 UTC, vfarah-if commented on datahub/bed_api/constants.py
> +        return result
Was a great scenario for me to use lambdas but your way is easier to read :) - Fixed

2021-06-09 07:25 UTC, vfarah-if commented on datahub/bed_api/factories.py
> +        else:
Fixed

2021-06-09 07:26 UTC, vfarah-if commented on datahub/bed_api/repositories.py
> +            and response['totalSize'] >= 1
Fixed

2021-06-09 07:28 UTC, vfarah-if commented on datahub/interaction/migrations/0001_initial_issue_types.yaml
> +  fields: {disabled_on: null, name: International Climate, order: 600.0}
Fixed

2021-06-09 07:28 UTC, vfarah-if commented on datahub/interaction/migrations/0001_initial_policy_areas.yaml
> +  fields: {disabled_on: null, name: 'Race to Zero, including Science Based Targets', order: 6500.0}
Fixed

2021-06-09 07:30 UTC, vfarah-if commented on datahub/bed_api/utils.py
> +        return data
Fixed

2021-06-09 07:33 UTC, vfarah-if commented on Makefile
> +	python -m black <Add File Here> --skip-string-normalization
Removed

2021-06-09 11:40 UTC, ambrozic approved these changes

2021-06-09 12:56 UTC, merged