Dependabot 2022 07 04
uktrade/data-hub-api pull request #4236
Opened 2022-07-04 15:20 UTC by onyela-o

### Description of change
 This week's Dependabot changes

### Checklist
* [x] Has this branch been rebased on top of the current `develop` branch?
* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/develop/docs/CONTRIBUTING.md) for more guidelines.

2022-07-04 15:28 UTC, cgsunkel requested changes
There is one upgrade that can't be merged in, everything else is fine though so you can just drop that commit.

2022-07-04 15:28 UTC, cgsunkel commented on requirements.in
> +boto3==1.24.22
We can't update `boto3` at the moment because the latest versions break our deployment.

2022-07-04 15:32 UTC, cgsunkel commented on requirements.in
> +boto3==1.24.22
I thought I'd put this on the Dependabot ignore list but it turns out I hadn't done it properly

2022-07-04 15:45 UTC, cgsunkel approved these changes

2022-07-05 05:16 UTC, marijnkampf approved these changes

2022-07-05 08:41 UTC, merged