Chore/dependencies 2022 11 07
uktrade/data-hub-api pull request #4377
Opened 2022-11-07 12:16 UTC by santoshdasa12345

### Description of change
This week Dependabot Updates

### Checklist

* [x] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [x] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2022-11-07 14:15 UTC, rachaelcodes approved these changes

2022-11-07 14:17 UTC, marijnkampf requested changes

2022-11-07 15:38 UTC, santoshdasa12345 commented on requirements-dev.txt
> +ipython==8.5.0
resolved

2022-11-08 08:19 UTC, marijnkampf commented on requirements-dev.txt
> +ipython==8.5.0
You'll need to run `pip-compile --output-file=requirements-dev.txt requirements-dev.in` to update the file.

2022-11-09 13:12 UTC, santoshdasa12345 commented on requirements-dev.txt
> +ipython==8.5.0
Updated and resolvedf

2022-11-09 14:41 UTC, marijnkampf approved these changes

2022-11-09 15:41 UTC, merged