WIP: Update advisor view to filter by date if needed
uktrade/data-hub-api pull request #5030
Opened 2023-11-23 08:36 UTC by PippoRaimondiDIT

### Description of change

### Checklist

* [ ] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2023-11-25 15:17 UTC, PippoRaimondiDIT commented
the field from the queryset looks like 'created_on': datetime.datetime(2023, 11, 25, 15, 16, 9, 187961, tzinfo=<UTC>)

i think this is the reason why the below filter on updated since doesn't work:

from datetime import datetime

from django.contrib.postgres.aggregates import ArrayAgg

from datahub.company.models import Company
from datahub.dataset.core.views import BaseDatasetView
from datahub.metadata.query_utils import get_sector_name_subquery
from datahub.metadata.utils import convert_usd_to_gbp


def parse_date(value):
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


class CompaniesDatasetView(BaseDatasetView):
    """
    A GET API view to return the data for all companies as required
    for syncing by Data-flow periodically.
    Data-flow uses the resulting response to insert data into Data workspace which can
    then be queried to create custom reports for users.
    """

    def get(self, request):
        """Endpoint which serves all records for Company Dataset"""
        dataset = self.get_dataset(request)
        paginator = self.pagination_class()
        page = paginator.paginate_queryset(dataset, request, view=self)
        self._enrich_data(page)
        return paginator.get_paginated_response(page)

    def get_dataset(self, request):
        """Returns list of Company records"""
        queryset = Company.objects.annotate(
            sector_name=get_sector_name_subquery('sector'),
            one_list_core_team_advisers=ArrayAgg('one_list_core_team_members__adviser_id'),
        ).values(
            'address_1',
            'address_2',
            'address_county',
            'address_country__name',
            'address_postcode',
            'address_area__name',
            'address_town',
            'archived',
            'archived_on',
            'archived_reason',
            'business_type__name',
            'company_number',
            'created_by_id',
            'created_on',
            'description',
            'duns_number',
            'export_experience_category__name',
            'global_headquarters_id',
            'global_ultimate_duns_number',
            'headquarter_type__name',
            'id',
            'is_number_of_employees_estimated',
            'is_turnover_estimated',
            'modified_on',
            'name',
            'number_of_employees',
            'one_list_account_owner_id',
            'one_list_tier__name',
            'one_list_core_team_advisers',
            'reference_code',
            'registered_address_1',
            'registered_address_2',
            'registered_address_country__name',
            'registered_address_county',
            'registered_address_postcode',
            'registered_address_area__name',
            'registered_address_town',
            'sector_name',
            'export_segment',
            'export_sub_segment',
            'trading_names',
            'turnover',
            'uk_region__name',
            'vat_number',
            'website',
            'is_out_of_business',
            'strategy',
        )
        updated_since = request.GET.get('updated_since')
        print(updated_since)
        if updated_since:
            updated_since_date = parse_date(updated_since)
            print(updated_since_date)
            if updated_since_date:
                print(queryset)
                queryset = queryset.filter(created_on__gt=updated_since_date)
                print(queryset)
                test=1

        return queryset

    def _enrich_data(self, dataset):
        for data in dataset:
            if data.get('turnover') is not None:
                data['turnover_gbp'] = convert_usd_to_gbp(data['turnover'])
            else:
                data['turnover_gbp'] = None
        return super()._enrich_data(dataset)

2023-12-04 10:18 UTC, Richard-Pentecost commented on datahub/dataset/company/views.py
> +            if updated_since_date:
Why do we need this if statement? Surely if we are in the `if updated_since` block, then `updated_since_date` will always be true

2023-12-04 10:19 UTC, Richard-Pentecost commented on datahub/dataset/company_export/views.py
> +            if updated_since_date:
Same comment as above

2023-12-04 10:19 UTC, Richard-Pentecost commented on datahub/dataset/company_export_country/views.py
> +            if updated_since_date:
same comment as above

2023-12-04 10:20 UTC, Richard-Pentecost commented on datahub/dataset/company_referral/views.py
> +            if updated_since_date:
Same comment as above

2023-12-04 10:20 UTC, Richard-Pentecost commented on datahub/dataset/contact/views.py
> +            if updated_since_date:
Same as above

2023-12-04 10:21 UTC, Richard-Pentecost commented on datahub/dataset/event/views.py
> +            if updated_since_date:
As above

2023-12-04 10:22 UTC, Richard-Pentecost commented on datahub/dataset/interaction/views.py
> +            if updated_since_date:
as above

2023-12-04 10:22 UTC, Richard-Pentecost commented on datahub/dataset/interaction_export_country/views.py
> +            if updated_since_date:
as above

2023-12-04 10:22 UTC, Richard-Pentecost commented on datahub/dataset/investment_project/views.py
> +            if updated_since_date:
as above

2023-12-04 10:22 UTC, Richard-Pentecost commented on datahub/dataset/order/views.py
> +            if updated_since_date:
as above

2023-12-04 10:24 UTC, Richard-Pentecost commented on datahub/dataset/user_event_log/views.py
> +            if updated_since_date:
as above

2023-12-05 10:19 UTC, DeanElliott96 requested changes
Looks good but I think it needs to be refactored a little to prevent the code repetition.

2023-12-05 10:19 UTC, DeanElliott96 commented on datahub/dataset/company/views.py
> +            if updated_since_date:
This seems to be the same change 11 times with the only difference being the field name.

Maybe this should be moved out to a util function or something to prevent repeating the same code?

2023-12-05 14:47 UTC, DeanElliott96 approved these changes

2023-12-05 15:29 UTC, merged