Add Export Win models.
uktrade/data-hub-api pull request #5034
Opened 2023-11-24 15:55 UTC by elcct

### Description of change

This adds remaining Export Win data models.

### Checklist

* [x] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [x] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2023-11-27 13:37 UTC, elcct commented on datahub/export_win/models.py
> +class CustomerResponse(BaseModel):
We will keep it in single file in this case.

2023-11-27 13:41 UTC, elcct commented on datahub/export_win/models.py
> +class Win(BaseModel):
In this case we will keep it in the single file.

2023-11-27 15:20 UTC, ince-dbt requested changes

2023-11-27 15:20 UTC, ince-dbt commented on datahub/cleanup/management/commands/delete_old_records.py
> +                DatetimeLessThanCleanupFilter('modified_on', TASK_EXPIRY_PERIOD),
Did we not say this will be CUSTOMER_RESPONSE_EXPIRY_PERIOD instead of TASK_EXPIRY_PERIOD??

2023-11-27 15:20 UTC, ince-dbt commented on datahub/cleanup/management/commands/delete_old_records.py
> +                DatetimeLessThanCleanupFilter('modified_on', TASK_EXPIRY_PERIOD),
Did we not say this will be WIN_EXPIRY_PERIOD instead of TASK_EXPIRY_PERIOD?

2023-11-29 09:47 UTC, ince-dbt approved these changes

2023-11-29 10:16 UTC, dredmonds approved these changes

2023-11-29 11:59 UTC, merged