Create management command to consume export potential report
uktrade/data-hub-api pull request #5217
Opened 2024-02-23 11:08 UTC by PippoRaimondiDIT

### Description of change

Scope of this PR:

- Create management command which consumes and saves export potential data from S3 into DH Company model
- Create celery task to run the management command daily 

### Checklist

* [ ] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2024-03-01 15:49 UTC, DeanElliott96 requested changes
Looks good, just a suggestion to remove non error handled code out the try except and to reduce some tabs.

2024-03-01 15:49 UTC, DeanElliott96 commented on datahub/dbmaintenance/management/commands/update_company_export_potential_date.py
> +                    logger.warning(f'Multiple companies found for: {company_number}')
To keep some code out the try except and to reduce the tabs, could this be?
```
for row in tqdm(rows, desc='Processing companies'):
    result = self._process_row(row, **options)
    if not result:
        continue

    company_number, export_potential = result
    try:
        company = Company.objects.get(company_number=company_number)
    except Company.DoesNotExist:
        logger.warning(f'Company not found for company number: {company_number}')
        continue
    except Company.MultipleObjectsReturned:
        logger.warning(f'Multiple companies found for: {company_number}')
        continue

    if company.export_potential == export_potential:
        continue

    company.export_potential = export_potential
    company.last_modified_potential = now().date()
    updates.append(company)

    if len(updates) >= BATCH_SIZE:
        self._update_batch(updates, options['simulate'])
        updates = []

```

2024-03-01 16:00 UTC, PippoRaimondiDIT commented on datahub/dbmaintenance/management/commands/update_company_export_potential_date.py
> +                    logger.warning(f'Multiple companies found for: {company_number}')
Nice one! thanks for the suggestion!

2024-03-05 12:43 UTC, DeanElliott96 approved these changes

2024-03-06 09:04 UTC, paulgain approved these changes

2024-03-06 09:52 UTC, merged