Add first and last sent dates to Win view
uktrade/data-hub-api pull request #5227
Opened 2024-02-26 16:52 UTC by elcct

### Description of change

This adds first and last sent notification dates (read only) to Win views.

If there is only one notification, the first and last sent dates will be equal.

### Checklist

* [x] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [x] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2024-02-26 18:15 UTC, paulgain approved these changes

2024-02-27 15:01 UTC, DeanElliott96 requested changes
Looks good but might need another table in the `select_related` and I'm unsure about what the `perform_create` code is for?

2024-02-27 15:58 UTC, elcct commented on datahub/export_win/views.py
> +        last_sent=Max('customer_response__tokens__created_on'),
This wouldn't help as we are only selecting earliest and latest `created_on` date from related tokens, so there is no need. I think `select_related` wouldn't work in this case anyway, due to how tokens are related. We could potentially use `prefetch_related`, but since we are not iterating over the related tokens nor accessing other token fields, that would be redundant.

2024-02-27 16:01 UTC, elcct commented on datahub/export_win/views.py
> +        serializer.instance = self.get_queryset().get(pk=instance.pk)
When new Win is created, the instance created in the serialiser does not have the extra annotated fields (`first_sent` and `last_sent`) so they are not being returned as it does not have access to the view's query set. This function replaces the serialiser instance with the one that has annotations and so the serialiser can include these fields in the response.

2024-02-27 16:40 UTC, DeanElliott96 commented on datahub/export_win/views.py
> +        serializer.instance = self.get_queryset().get(pk=instance.pk)
Thanks for explaining!

2024-02-27 16:41 UTC, DeanElliott96 approved these changes

2024-02-28 09:33 UTC, merged