Create update_interactions_to_new_adviser.py
uktrade/data-hub-api pull request #5544
Opened 2024-07-23 09:06 UTC by bau123

Change interaction records with incorrect adviser

### Checklist

* [ ] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2024-07-23 11:31 UTC, dredmonds approved these changes

2024-07-25 07:17 UTC, marijnkampf requested changes
There are no tests for this file.

2024-07-25 07:17 UTC, marijnkampf commented on datahub/dbmaintenance/management/commands/update_interactions_to_new_adviser.py
> +    help = 'Updates interaction advisers to a new team with the history up to a certain date'
If the simulate parameter can be passed from the command line it should be included in the help.

2024-07-29 10:13 UTC, bau123 commented on datahub/dbmaintenance/management/commands/update_interactions_to_new_adviser.py
> +        if not interaction_participants:
Can have more than one to check so we can ignore this

2024-07-29 11:08 UTC, bau123 commented on datahub/dbmaintenance/management/commands/update_interactions_to_new_adviser.py
> +    help = 'Updates interaction advisers to a new team with the history up to a certain date'
done

2024-08-01 07:40 UTC, marijnkampf approved these changes

2024-08-01 09:08 UTC, merged