Cls2 898 eyblead serializers views
uktrade/data-hub-api pull request #5598
Opened 2024-08-21 15:02 UTC by samuele-mattiuzzo

### Description of change

### Checklist

* [ ] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2024-08-28 08:28 UTC, p3dr0migue1 commented on datahub/investment_lead/serializers.py
> +ALL_FIELDS = [
I think you can now specify all fields with `"__all__"` like in Django, this feature was introduced in [DRF 3.5](https://www.django-rest-framework.org/community/3.5-announcement/#modelserializer-fields-and-exclude).

Essentially:
```python
class Meta:
    model = EYBLead
    fields = "__all__"
```

2024-08-28 08:28 UTC, p3dr0migue1 approved these changes

2024-08-28 09:43 UTC, oliverjwroberts requested changes
Thanks for this Sam. Just a couple of comments from me. As we discussed in your handover, I'll make the amendments and take this forward on your behalf.

2024-08-28 10:03 UTC, oliverjwroberts commented on datahub/investment_lead/serializers.py
> +ALL_FIELDS = [
I believe you can do this, however, the convention appears to be explicility listing fields (e.g. see serialiser for Investment Projects and Companies). We may need fine-grain control in subsequent work, so I'm tempted to leave it in for now, if that's okay?

2024-08-29 08:25 UTC, oliverjwroberts commented on datahub/investment_lead/serializers.py
> +ALL_FIELDS = [
Yes I think we could have, thanks! However, we have now decided to use a subset of fields (and will also need the finer-grain control for future changes) and so will leave it as explicit lists.

2024-08-29 08:26 UTC, oliverjwroberts commented on datahub/investment_lead/serializers.py
> +        if data['triage_hashed_uuid'] != data['user_hashed_uuid']:
Will chase the team for clarification on this. However, for now, this is acceptable for our MVP (and can be easily modified as and when).

2024-08-29 08:27 UTC, oliverjwroberts commented on datahub/investment_lead/test/test_serializers.py
> +        error_message = str(serial_error.value.detail['non_field_errors'][0])
I realise you probably don't want to inspect the captured logs, rather the validation errors raised by the serailser. You can do so via: 

```python
assert UUIDS_ERROR_MESSAGE in eyb_serializer.errors['non_field_errors']
```

2024-08-29 08:27 UTC, oliverjwroberts commented on datahub/investment_lead/test/test_serializers.py
> +        eyb_object = EYBLead.objects.first()
Test was refactored.

2024-08-29 08:28 UTC, oliverjwroberts commented on datahub/investment_lead/views.py
> +    def create(self, request):
POST route modified to accept a list of instances.

2024-08-29 08:54 UTC, oliverjwroberts commented on datahub/investment_lead/views.py
> +            raise
Rather than raise an error, I've logged the response dictionary which outlines result/errors that occurred for each lead processed.

2024-09-03 09:33 UTC, elcct approved these changes

2024-09-03 09:52 UTC, oliverjwroberts approved these changes

2024-09-03 09:57 UTC, merged