Dependabot 2024-09-16
uktrade/data-hub-api pull request #5641
Opened 2024-09-17 15:15 UTC by samuele-mattiuzzo

### Description of change

### Checklist

* [x] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2024-09-17 15:37 UTC, swenban approved these changes

2024-09-17 15:41 UTC, baarkerlounger approved these changes

2024-09-17 15:43 UTC, oliverjwroberts requested changes
I should've said something before, but we decided a couple months back that we would not upgrade any Data Hub apps to Django 5.x until 5.2 is released (as it will have long term support). Until then, we should remain on 4.2.x.

While you're reverting it, and if you're able to, it might be worth commenting on Dependabot's PR and telling it to ignore Django 5.x versions for now.

Clearly we should've documented this better, for which I apologise.

2024-09-18 11:16 UTC, oliverjwroberts approved these changes

2024-09-18 11:20 UTC, swenban approved these changes

2024-09-18 11:40 UTC, merged