TET-813: Company Activity Data Ingestion
uktrade/data-hub-api pull request #5658
Opened 2024-09-23 14:25 UTC by baarkerlounger

### Description of change

Company Activity data will be written to an S3 bucket in the Datahub account by Data Flow once a day. The paths will have the form:

`S3://<BucketName>/data-flow/exports/<DataSourceName>/<DateTime>/file.gz`

The bucket has a 90 day lifecycle policy after which files are deleted. 

- This PR adds a scheduled job on the short running queue that runs every 10 minutes (TBC). New files are expected daily but we can't rely on them being written at a specific time.
- The job checks whether there are any new, not yet imported files. It adds a Django model + Postgres table to track already ingested files. 
- For any new files it finds, it queues another job to ingest that file into the Django model + Postgres table for that data source
- It adds a new dependency - [Smart Open](https://github.com/piskvorky/smart_open) for Streaming the zipped json files from S3 as they may be very large, and a new dev dependency [Moto](https://docs.getmoto.org/en/latest/index.html) for mocking AWS services in tests

### Checklist

* [x] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [x] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2024-09-26 16:36 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_company_activity.py
> +BUCKET = 'data-flow-bucket' + env('environment', default='')
Do we have an env var already for this or is there a Django setting/method we can use?

2024-09-26 16:37 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_company_activity.py
> +        return previously_ingested.count() > 0
Should be a more idiomatic way of doing this

2024-09-26 16:44 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_company_activity.py
> +            rq_queue.enqueue(GreatIngestionTask.ingest, BUCKET, latest_file)
Check if we should be using a wrapper here

2024-10-01 14:51 UTC, baarkerlounger commented on datahub/company_activity/models/great.py
> +    actor_dit_blacklisted_reason = models.CharField(max_length=MAX_LENGTH, null=True)
We get `null` rather than empty strings in the Great data so I think it makes sense to maintain that.

2024-10-01 14:53 UTC, baarkerlounger commented on datahub/company_activity/models/great.py
> +class Great(models.Model):
Don't think this is necessary/beneficial for now unless reviewers think otherwise.

2024-10-01 16:05 UTC, DeanElliott96 requested changes
Nice work! Couple small changes and suggestions. Not sure what the best approach would be to track the files failed, in progress etc.

2024-10-01 16:08 UTC, baarkerlounger commented on datahub/company_activity/models/ingested_file.py
> +    created_on = models.DateTimeField(auto_now_add=True)
Yes, I didn't end up having a use case for adding it really. Happy to add it if there is one (though that could maybe also be a separate PR).

2024-10-01 16:14 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_company_activity.py
> +        return False
Yep that's the idea.

I think having a status in the model visible in the model is nice, but has the drawback of needing to make sure the status is correct and I can see some edge cases that would add complexity. e.g:

1) A job for the file is queued, but redis is flushed before it's run (and it's never picked up so hasn't technically failed - no callback is run). 
2) Failed jobs require a callback to update the status

2024-10-01 16:18 UTC, baarkerlounger commented on datahub/company_activity/tests/factories.py
> +    data_opportunity_urls = 'http://moore.com/listpost.html'
I wanted a hard coded set so I can test the values changing in the `update_or_create` without risk of it being flakey

2024-10-01 16:39 UTC, DeanElliott96 commented on datahub/company_activity/tasks/ingest_company_activity.py
> +        return False
Yeah I agree, this does seem more robust!

2024-10-01 16:59 UTC, DeanElliott96 commented on datahub/company_activity/tasks/ingest_company_activity.py
> +GREAT_PREFIX = PREFIX + 'GreatGovUKFormsPipeline/'
I guess the only reason is consistency in the codebase.

For me, I don't think its unreadable but I do have a personal preference towards f strings 😄.

2024-10-02 08:02 UTC, oliverjwroberts approved these changes
PR adds foundational functionality to ingest company activity data from an S3 bucket at regular intervals.

Some minor comments from me, but happy to approve PR in its current state (as long as you fix closing of the file that @DeanElliott96 highighted). I really like the cron job testing you've done, nice work!

2024-10-02 08:27 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_great_data.py
> +        self._countries = Country.objects.all()
Could go either way I think, but yeah it's the querying that's the most important thing happening I think

2024-10-02 08:28 UTC, baarkerlounger commented on datahub/company_activity/tests/factories.py
> +    data_opportunity_urls = 'http://moore.com/listpost.html'
What's the advantage of using Faker here? Are there any tangible benefits or is it more for the benefit of future PRs?

2024-10-02 08:31 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_company_activity.py
> +                )
Done

2024-10-02 08:31 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_company_activity.py
> +GREAT_PREFIX = PREFIX + 'GreatGovUKFormsPipeline/'
Done

2024-10-02 08:31 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_great_data.py
> +        IngestedFile.objects.create(filepath=file)
Done

2024-10-02 08:31 UTC, baarkerlounger commented on datahub/company_activity/tests/test_tasks/test_great_ingestion_task.py
> +    return GREAT_PREFIX + '20240920T000000/full_ingestion.jsonl.gz'
Done

2024-10-02 08:32 UTC, baarkerlounger commented on datahub/company_activity/tests/test_tasks/test_great_ingestion_task.py
> +        assert sentry_event['logentry']['message'] == expected_message
Specifically Sentry since I want to be alerted if it happens. Which I think my test does (assuming Sentry is configured correctly)

2024-10-02 08:37 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_great_data.py
> +        countries = self._countries.filter(iso_alpha2_code=country_code)
This is nice. Done.

2024-10-02 08:38 UTC, baarkerlounger commented on datahub/company_activity/tasks/ingest_great_data.py
> +            'data_company_size': data.get('company_size', ''),
Yeah I intend to change this, just don't want to need to wait for confirmation on the data model since this work is already large and blocking other things.

Will come back to it if we get confirmation from the Great team.

2024-10-02 08:48 UTC, baarkerlounger commented on datahub/company_activity/models/great.py
> +    data_opportunities = models.CharField(max_length=MAX_LENGTH)
Agree, similar to above just going to wait to confirm that's correct so will probably make the change along with the `company_size` field above later, once we've confirmed the data model.

2024-10-02 09:13 UTC, DeanElliott96 commented on datahub/company_activity/tests/factories.py
> +    data_opportunity_urls = 'http://moore.com/listpost.html'
For faker, the benefit would be testing against different data every time the test is run, simulating how we will be receiving the real data. Happy to approve without but would recommend adding it in for future PRs.

2024-10-02 09:14 UTC, DeanElliott96 approved these changes

2024-10-02 09:23 UTC, oliverjwroberts commented on datahub/company_activity/tests/test_tasks/test_great_ingestion_task.py
> +        assert sentry_event['logentry']['message'] == expected_message
Do we know if all logged messages get sent to Sentry? Should we be testing that all logged messages get sent to Sentry in a centralised manner, rather than individual tests? I'm not saying I want you to change anything now (happy to approve the PR as is), but maybe something that we agree on as devs for consistency going forward.

2024-10-02 09:24 UTC, oliverjwroberts approved these changes

2024-10-02 09:26 UTC, merged