Add omis order to company activity
uktrade/data-hub-api pull request #5709
Opened 2024-10-17 08:32 UTC by bau123

Add omis order to company activity

### Checklist

* [ ] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2024-10-17 08:36 UTC, baarkerlounger commented on datahub/company_activity/models/company_activity.py
> +    order = models.ForeignKey(
Worth naming this `omis_order` to avoid any confusion with sorting order or keyword clashes elsewhere in the code?

2024-10-17 08:37 UTC, baarkerlounger commented on datahub/company_activity/models/company_activity.py
> +            'If related to an omis order, must not have relations to any other activity ' '(referral, event etc)'
Why is this true/where does it come from?

2024-10-18 10:29 UTC, bau123 commented on datahub/company_activity/models/company_activity.py
> +    order = models.ForeignKey(
i think keeping it as `order` makes more sense since the models in the company activity follow this format and other cases where `order` is use, we don't call it as `omis_order`

2024-10-18 10:30 UTC, bau123 commented on datahub/company_activity/models/company_activity.py
> +            'If related to an omis order, must not have relations to any other activity ' '(referral, event etc)'
This is just help text for when add orders in to the company activity model. I followed the same help text as the other models used

2024-10-23 14:02 UTC, baarkerlounger commented on datahub/omis/order/test/test_models.py
> +        Test save does not save to the `CompanyActivity` model if it already exists.
These should maybe be two separate tests?

2024-10-23 14:45 UTC, bau123 commented on datahub/omis/order/test/test_models.py
> +        Test save does not save to the `CompanyActivity` model if it already exists.
More of a bad description than it needing to be two separate test

2024-10-23 15:16 UTC, DeanElliott96 requested changes

2024-10-23 15:16 UTC, DeanElliott96 commented on datahub/omis/order/models.py
> +                return
Would probably be best to update with these suggestions preventing an additional DB read.

2024-10-23 15:16 UTC, DeanElliott96 commented on datahub/omis/order/models.py
> +                    'company_id': self.company.id,
Would probably be best to update with these suggestions preventing an additional DB read.

2024-10-23 15:16 UTC, DeanElliott96 commented on datahub/search/sync_object.py
> +        return
Might be worth adding the test here, could probably copy most of the one here: https://github.com/uktrade/data-hub-api/blob/fc4b35968492a33e2bbdb9554056c9f358a11bf2/datahub/search/test/test_sync_object.py#L21

You would just delete the object before sending it to the `sync_related_objects_async` and ensure its not on opensearch.

2024-10-24 08:49 UTC, bau123 commented on datahub/omis/order/models.py
> +                return
done

2024-10-24 08:49 UTC, bau123 commented on datahub/omis/order/models.py
> +                    'company_id': self.company.id,
done

2024-10-24 08:49 UTC, bau123 commented on datahub/search/sync_object.py
> +        return
done

2024-10-24 08:51 UTC, baarkerlounger commented on datahub/omis/order/test/test_models.py
> +        Test save does not save to the `CompanyActivity` model if it already exists.
How do you mean? It sounds like it's testing two separate things here?

2024-10-24 08:52 UTC, baarkerlounger commented on datahub/omis/order/test/test_models.py
> +        assert CompanyActivity.objects.all().count() == 0
Any reason not to use `.exists()` here?

2024-10-24 08:52 UTC, baarkerlounger commented on datahub/omis/order/test/test_models.py
> +        assert CompanyActivity.objects.all().count() == 0
And here

2024-10-24 08:54 UTC, bau123 commented on datahub/omis/order/test/test_models.py
> +        assert CompanyActivity.objects.all().count() == 0
Added

2024-10-24 08:54 UTC, bau123 commented on datahub/omis/order/test/test_models.py
> +        assert CompanyActivity.objects.all().count() == 0
Added

2024-10-24 10:32 UTC, bau123 commented on datahub/omis/order/test/test_models.py
> +        Test save does not save to the `CompanyActivity` model if it already exists.
I've changed the description to:
Test save also saves to the `CompanyActivity` model and does not save to the `CompanyActivity` model if it already exists.

2024-10-24 13:06 UTC, baarkerlounger approved these changes

2024-10-25 09:40 UTC, baarkerlounger commented on datahub/search/sync_object.py
> +        logger.exception(
Should there be a test for these new logs?

2024-10-25 10:24 UTC, bau123 commented on datahub/search/sync_object.py
> +        logger.exception(
I've now added a test for this

2024-10-25 10:51 UTC, bau123 commented on datahub/search/test/test_sync_object.py
> +        f'SimpleModel matching query does not exist. '
changed

2024-10-25 10:51 UTC, bau123 commented on datahub/search/test/test_sync_object.py
> +        f'SimpleModel matching query does not exist. '
changed

2024-10-25 11:47 UTC, merged