removing add investmemnt project button
uktrade/data-hub-api pull request #5744
Opened 2024-10-30 14:15 UTC by santoshdasa12345

### Description of change

### Checklist

* [ ] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [ ] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2024-10-30 15:07 UTC, oliverjwroberts requested changes
Serialiser changes look good to me, nice work! Please can you add a test to assert this field is present in the API response going forward?

2024-10-30 21:18 UTC, oliverjwroberts approved these changes

2024-10-31 11:50 UTC, ince-dbt approved these changes

2024-10-31 11:53 UTC, dredmonds approved these changes
Approved this PR and left minor comment for your action.

2024-10-31 11:53 UTC, dredmonds commented on datahub/investment_lead/serializers.py
> +    investment_projects = NestedRelatedField(InvestmentProject, many=True)
It would be robust to add an assertion this field into `https://github.com/uktrade/data-hub-api/blob/5e5455d3fc81e56cbf8bc8256f7beb16b83139da/datahub/investment_lead/test/test_serializers.py` test specs.

2024-10-31 11:58 UTC, samuele-mattiuzzo commented on datahub/investment_lead/serializers.py
> +    investment_projects = NestedRelatedField(InvestmentProject, many=True)
@dredmonds we test the serializer's behaviour through a separate utils

https://github.com/uktrade/data-hub-api/blob/b8c56f3031757542d2eed28482fb66775e4fd16a/datahub/investment_lead/test/utils.py#L148

2024-10-31 12:06 UTC, merged