Extract common ingestion tasks
uktrade/data-hub-api pull request #5847
Opened 2024-12-09 07:42 UTC by oliverjwroberts

### Description of change

This PR creates a new _ingest_ sub-app that contains base functionality and utilities for ingesting objects from S3 buckets. 

Notably, it adds:
- A `get_s3_client()` function that returns a boto3 S3 client, either using the automatic endpoint URL or localstack's if the env variable `S3_LOCAL_ENDPOINT_URL` is set.
- An `S3ObjectProcessor` class for processing objects located at a specified prefix within an S3 bucket.
- Several constants for when using S3 buckets.
- A new `ingest.IngestedObject` model, that mirrors the functionality of `company_activity.IngestedFile`.
- A `BaseObjectIdentificationTask` class for identifying new objects in S3 and determining if they should be ingested.
- A `BaseObjectIngestionTask` class for ingesting a specified object from S3.

The _BaseObject...Task_ classes are intended to be inherited for each dataset that we wish to ingest. The class methods can be overridden to tailor the tasks to the specific dataset; the idea being that only minimal code changes are needed to do so.

In terms of testing, it also modifies/adds:
- An `s3_client` fixture
- An `s3_object_processor` fixture
- An `test_object_tuples` fixture which can be used to generate some object definitions for testing. This fixture also uses the utility function `compressed_json_faker` to serialize the contents and compress them into a `.jsonl.gz` object.
- An `upload_objects_to_s3` function that can be used to upload objects to a test S3 bucket.

### Checklist

* [x] Has this branch been rebased on top of the current `main` branch?

  <details>
  <summary>Explanation</summary>
  
  The branch should not be stale or have conflicts at the time reviews are requested.
  
  </details>

* [x] Is the CircleCI build passing?

### General points

<details>
<summary><strong>Other things to check</strong></summary><p></p>

* Make sure `fixtures/test_data.yaml` is maintained when updating models
* Consider the admin site when making changes to models
* Use select-/prefetch-related field lists in views and search apps, and update them when fields are added
* Make sure the README is updated e.g. when adding new environment variables

</details>

See [docs/CONTRIBUTING.md](https://github.com/uktrade/data-hub-api/blob/main/docs/CONTRIBUTING.md) for more guidelines.

2024-12-09 10:48 UTC, baarkerlounger commented on datahub/ingest/migrations/0001_initial.py
> +class Migration(migrations.Migration):
What's your plan for moving the data?

2024-12-09 10:49 UTC, baarkerlounger commented on datahub/ingest/tasks.py
> +        # Check running jobs
Could maybe extract this into a `is_job_running` method rather than adding a comment?

2024-12-09 10:50 UTC, baarkerlounger commented on datahub/ingest/tasks.py
> +        # Record ingestion
Could also be a method perhaps

2024-12-10 07:11 UTC, oliverjwroberts commented on datahub/ingest/migrations/0001_initial.py
> +class Migration(migrations.Migration):
My plan was to create a management command; probably at the same time I plug in the first ingestion tasks to this new common functionality. That way I can test it to ensure all instances are copied over correctly and it can be run multiple times while we refactor all ingestion tasks.

2024-12-10 07:12 UTC, oliverjwroberts commented on datahub/ingest/tasks.py
> +        # Check running jobs
Yes! I've made that change.

2024-12-10 07:13 UTC, oliverjwroberts commented on datahub/ingest/tasks.py
> +        # Record ingestion
Agreed. Same with the logging of various metrics (created, updated, failed, and skipped). I've made the changes in the new commit.

2024-12-11 09:37 UTC, baarkerlounger commented on datahub/ingest/utils.py
> +def upload_objects_to_s3(
Should this be in `ingest/test/utils.py` or do we actually use it outside of tests?

2024-12-11 09:38 UTC, baarkerlounger commented on datahub/ingest/tasks.py
> +        - Number of and list of instance id's that have been created
No `'` on `ids`?

2024-12-11 09:41 UTC, baarkerlounger approved these changes
Looks good. I know preference is generally for smaller PRs but I'd say in cases like this it would be worth including at least one existing ingestion task to use this mechanism. Helps show it works, and makes it easier to review the new generic code side by side with the old being removed.

2024-12-11 10:12 UTC, oliverjwroberts commented on datahub/ingest/utils.py
> +def upload_objects_to_s3(
We don't at the moment; but it could be. It could be used to upload files to the localstack container during development, or buckets in the deployed environments.

2024-12-11 10:17 UTC, baarkerlounger commented on datahub/ingest/utils.py
> +def upload_objects_to_s3(
Fair enough 👍

2024-12-11 10:17 UTC, oliverjwroberts commented
@baarkerlounger I was very conscious of how large this PR already is, but I agree, it probably would be easier to see a real example. I did attempt to describe an example in the docstring, but appreciate it's not the same. I was planning to plug the EYB ingestion tasks into this common functionality next; I wonder if it would be useful see that first before merging this in?

2024-12-11 15:48 UTC, DeanElliott96 requested changes
Looks good, just a few suggestions/changes.

2024-12-11 16:15 UTC, DeanElliott96 commented on datahub/ingest/tasks.py
> +        return False
Nope, leftover from copy paste.

2024-12-12 11:11 UTC, oliverjwroberts commented on datahub/ingest/boto3.py
> +        return [obj.get('Key') for obj in response.get('Contents', [])]
Nice spot and your suggestion is a much better approach, thanks. Will fix now.

2024-12-12 11:25 UTC, oliverjwroberts commented on datahub/ingest/boto3.py
> +    if settings.S3_LOCAL_ENDPOINT_URL:
I do wonder if this should be in local or dev settings instead?

2024-12-12 11:31 UTC, DeanElliott96 commented on datahub/ingest/boto3.py
> +    if settings.S3_LOCAL_ENDPOINT_URL:
I done a search for it and never seen it but its been there for a month, my bad!

2024-12-12 11:32 UTC, DeanElliott96 commented on datahub/ingest/boto3.py
> +    if settings.S3_LOCAL_ENDPOINT_URL:
I guess since its an environment variable, common is fine?

2024-12-12 11:35 UTC, DeanElliott96 approved these changes
Looks great! Once merged I will try using it with Stova.

2024-12-12 12:43 UTC, merged